# Generated by Django 4.2.6 on 2023-10-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Classic', 'Classic'), ('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Historical', 'Historical'), ('Biography', 'Biography'), ('Psychology', 'Psychology')], max_length=15)),
                ('release_date', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.writer')),
            ],
        ),
    ]
